-- 1. Tabella ASSET (La tua anagrafica)
-- Normalizza i nomi. Se l'AI dice "Oro", noi lo salviamo come 'XAUUSD'.
create table if not exists assets (
  ticker text primary key, -- Es: 'XAUUSD', 'EURUSD', 'SPX500'
  name text,               -- Es: 'Gold', 'Euro Dollaro'
  type text                -- 'COMMODITY', 'FOREX', 'INDEX', 'CRYPTO', 'STOCK'
);

-- Popoliamo qualche asset di base per evitare errori di Foreign Key iniziali
insert into assets (ticker, name, type) values 
('XAUUSD', 'Gold', 'COMMODITY'),
('EURUSD', 'Euro Dollar', 'FOREX'),
('BTCUSD', 'Bitcoin', 'CRYPTO'),
('SPX500', 'S&P 500', 'INDEX')
('NQ100', 'Nasdaq', 'INDEX')
('DJ30', 'Dow Jones', 'INDEX')

on conflict do nothing;

-- 2. Tabella SOURCES (I canali YouTube)
create table if not exists sources (
  id bigint generated by default as identity primary key,
  name text unique not null,
  base_url text
);

-- 3. Tabella INTELLIGENCE_FEED (Il contenitore video)
create table if not exists intelligence_feed (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  source_id bigint references sources(id),
  title text,
  url text unique not null,
  published_at timestamp with time zone,
  content text, -- Trascrizione completa
  summary text, -- Riassunto generale
  raw_metadata jsonb
);

-- 4. Tabella MARKET_INSIGHTS (L'intelligenza estratta)
-- Qui finiscono i dati strutturati per Asset
create table if not exists market_insights (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  video_id bigint references intelligence_feed(id) on delete cascade,
  asset_ticker text, -- Non mettiamo FK stretta per permettere all'AI di trovare nuovi ticker, ma consigliato normalizzare
  sentiment text check (sentiment in ('BULLISH', 'BEARISH', 'NEUTRAL')),
  timeframe text, -- 'SHORT', 'MEDIUM', 'LONG'
  key_levels text,
  ai_reasoning text
);

-- 5. Tabella TECHNICAL_SIGNALS (I tuoi FVG manuali/automatici)
create table if not exists technical_signals (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  asset_ticker text references assets(ticker),
  pattern text, -- 'FVG_H4', 'BREAKOUT', 'RETEST'
  direction text check (direction in ('LONG', 'SHORT')),
  status text default 'PENDING', -- 'PENDING', 'ACTIVE', 'FILLED', 'STOPPED'
  notes text
);