-- =============================================================================
-- 1. PULIZIA TOTALE (Reset)
-- =============================================================================
DROP TABLE IF EXISTS technical_signals CASCADE;
DROP TABLE IF EXISTS market_insights CASCADE;
DROP TABLE IF EXISTS intelligence_feed CASCADE;
DROP TABLE IF EXISTS sources CASCADE;
DROP TABLE IF EXISTS assets CASCADE;

-- =============================================================================
-- 2. TABELLA ASSETS (Anagrafica Strumenti)
-- =============================================================================
CREATE TABLE assets (
  ticker TEXT PRIMARY KEY,
  name TEXT,
  type TEXT -- 'COMMODITY', 'FOREX', 'STOCK', 'INDEX', 'CRYPTO'
);

-- Inserimento massivo (DJ30, US100, US500, Forex, Commodities)
INSERT INTO assets (ticker, name, type) VALUES 
-- 1. INDICI
('SPX500', 'S&P 500 Index', 'INDEX'),
('NQ100', 'Nasdaq 100 Index', 'INDEX'),
('DJ30', 'Dow Jones 30 Index', 'INDEX'),
('RUT2000', 'Russell 2000', 'INDEX'),
('DXY', 'US Dollar Index', 'INDEX'),
('VIX', 'Volatility Index', 'INDEX'),
('DAX40', 'DAX 40 Germany', 'INDEX'),
('FTSE100', 'FTSE 100 UK', 'INDEX'),
('CAC40', 'CAC 40 France', 'INDEX'),
('FTSEMIB', 'FTSE MIB Italy', 'INDEX'),
('IBEX35', 'IBEX 35 Spain', 'INDEX'),
('ESTX50', 'Euro Stoxx 50', 'INDEX'),
('NIKKEI225', 'Nikkei 225 Japan', 'INDEX'),
('HSI50', 'Hang Seng Hong Kong', 'INDEX'),
('NIFTY50', 'Nifty 50 India', 'INDEX'),
('CHINA50', 'China A50', 'INDEX'),

-- 2. FOREX
('EURUSD', 'Euro / US Dollar', 'FOREX'),
('GBPUSD', 'British Pound / US Dollar', 'FOREX'),
('USDJPY', 'US Dollar / Japanese Yen', 'FOREX'),
('USDCHF', 'US Dollar / Swiss Franc', 'FOREX'),
('USDCAD', 'US Dollar / Canadian Dollar', 'FOREX'),
('AUDUSD', 'Australian Dollar / US Dollar', 'FOREX'),
('NZDUSD', 'New Zealand Dollar / US Dollar', 'FOREX'),
('EURGBP', 'Euro / British Pound', 'FOREX'),
('EURJPY', 'Euro / Japanese Yen', 'FOREX'),
('EURCHF', 'Euro / Swiss Franc', 'FOREX'),
('GBPJPY', 'British Pound / Japanese Yen', 'FOREX'),
('AUDJPY', 'Australian Dollar / Japanese Yen', 'FOREX'),
('CADJPY', 'Canadian Dollar / Japanese Yen', 'FOREX'),
('EURAUD', 'Euro / Australian Dollar', 'FOREX'),
('GBPAUD', 'British Pound / Australian Dollar', 'FOREX'),
('USDMXN', 'US Dollar / Mexican Peso', 'FOREX'),
('USDZAR', 'US Dollar / South African Rand', 'FOREX'),
('USDTRY', 'US Dollar / Turkish Lira', 'FOREX'),

-- 3. COMMODITIES
('XAUUSD', 'Gold Spot', 'COMMODITY'),
('XAGUSD', 'Silver Spot', 'COMMODITY'),
('XPTUSD', 'Platinum Spot', 'COMMODITY'),
('HG1!', 'Copper Futures', 'COMMODITY'),
('WTI', 'Crude Oil WTI', 'COMMODITY'),
('BRENT', 'Crude Oil Brent', 'COMMODITY'),
('NGAS', 'Natural Gas', 'COMMODITY'),
('URANIUM', 'Uranium', 'COMMODITY'),
('CORN', 'Corn Futures', 'COMMODITY'),
('WHEAT', 'Wheat Futures', 'COMMODITY'),
('SOY', 'Soybean Futures', 'COMMODITY'),
('COFFEE', 'Coffee Futures', 'COMMODITY'),
('SUGAR', 'Sugar Futures', 'COMMODITY'),
('COCOA', 'Cocoa Futures', 'COMMODITY'),

-- 4. CRYPTO
('BTCUSD', 'Bitcoin', 'CRYPTO'),
('ETHUSD', 'Ethereum', 'CRYPTO'),
('SOLUSD', 'Solana', 'CRYPTO'),
('XRPUSD', 'Ripple', 'CRYPTO'),
('BNBUSD', 'Binance Coin', 'CRYPTO'),
('DOGEUSD', 'Dogecoin', 'CRYPTO'),
('ADAUSD', 'Cardano', 'CRYPTO'),
('AVAXUSD', 'Avalanche', 'CRYPTO'),
('DOTUSD', 'Polkadot', 'CRYPTO'),
('LINKUSD', 'Chainlink', 'CRYPTO'),

-- 5. STOCKS (Mag 7, DJ30, Nasdaq Top)
('NVDA', 'NVIDIA Corp.', 'STOCK'),
('MSFT', 'Microsoft Corp.', 'STOCK'),
('AAPL', 'Apple Inc.', 'STOCK'),
('GOOGL', 'Alphabet Inc.', 'STOCK'),
('AMZN', 'Amazon.com Inc.', 'STOCK'),
('META', 'Meta Platforms', 'STOCK'),
('TSLA', 'Tesla Inc.', 'STOCK'),
('AVGO', 'Broadcom Inc.', 'STOCK'),
('AMD', 'Advanced Micro Devices', 'STOCK'),
('NFLX', 'Netflix Inc.', 'STOCK'),
('ADBE', 'Adobe Inc.', 'STOCK'),
('CRM', 'Salesforce Inc.', 'STOCK'),
('ORCL', 'Oracle Corp.', 'STOCK'),
('CSCO', 'Cisco Systems', 'STOCK'),
('INTC', 'Intel Corp.', 'STOCK'),
('QCOM', 'Qualcomm Inc.', 'STOCK'),
('JPM', 'JPMorgan Chase', 'STOCK'),
('GS', 'Goldman Sachs', 'STOCK'),
('V', 'Visa Inc.', 'STOCK'),
('MA', 'Mastercard Inc.', 'STOCK'),
('WMT', 'Walmart Inc.', 'STOCK'),
('KO', 'Coca-Cola Co.', 'STOCK'),
('DIS', 'Walt Disney Co.', 'STOCK'),
('BA', 'Boeing Co.', 'STOCK'),
('CAT', 'Caterpillar Inc.', 'STOCK'),
('LLY', 'Eli Lilly', 'STOCK'),
('XOM', 'Exxon Mobil', 'STOCK'),
('UNH', 'UnitedHealth Group', 'STOCK'),

-- 6. BONDS
('US10Y', 'US 10Y Yield', 'BOND'),
('US02Y', 'US 2Y Yield', 'BOND'),
('DE10Y', 'Germany 10Y Yield', 'BOND'),
('IT10Y', 'Italy 10Y Yield', 'BOND')
ON CONFLICT (ticker) DO NOTHING;

-- =============================================================================
-- 3. TABELLA SOURCES (Canali Youtube)
-- =============================================================================
CREATE TABLE sources (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  base_url TEXT
);

-- =============================================================================
-- 4. TABELLA INTELLIGENCE_FEED (Il Video)
-- =============================================================================
CREATE TABLE intelligence_feed (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  source_id BIGINT REFERENCES sources(id),
  title TEXT,
  url TEXT UNIQUE NOT NULL,
  published_at TIMESTAMP WITH TIME ZONE,
  content TEXT, -- Trascrizione
  summary TEXT, -- 'video_summary' dal prompt
  macro_sentiment TEXT, -- 'macro_sentiment' dal prompt
  raw_metadata JSONB
);

-- =============================================================================
-- 5. TABELLA MARKET_INSIGHTS (L'Analisi specifica per Asset)
-- =============================================================================
CREATE TABLE market_insights (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  video_id BIGINT REFERENCES intelligence_feed(id) ON DELETE CASCADE,
  
  -- Info Asset
  asset_ticker TEXT NOT NULL,
  asset_name TEXT,
  channel_style TEXT, -- 'Tecnica', 'Fondamentale', 'Quantitativa'
  
  -- Sentiment e Segnale (Allineati al prompt)
  sentiment TEXT,      -- 'Bullish', 'Bearish', 'Neutral/Range'
  recommendation TEXT, -- 'LONG', 'SHORT', 'WATCH', 'HOLD'
  time_horizon TEXT,   -- 'Intraday', 'Multiday/Weekly', etc.
  
  -- Livelli Operativi (Split per precisione SMC/ICT)
  entry_zone TEXT,
  target_price TEXT,
  stop_invalidation TEXT,
  
  -- Contenuti UI
  key_drivers JSONB,   -- Salviamo la lista ["driver1", "driver2"]
  summary_card TEXT,    -- Frase breve UI
  
  -- Extra
  confidence_score INTEGER DEFAULT 5
);

-- =============================================================================
-- 6. INDICI E POLICY
-- =============================================================================
CREATE INDEX idx_insights_ticker ON market_insights(asset_ticker);
CREATE INDEX idx_insights_style ON market_insights(channel_style);

ALTER TABLE intelligence_feed ENABLE ROW LEVEL SECURITY;
ALTER TABLE market_insights ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public read access" ON market_insights FOR SELECT USING (true);
CREATE POLICY "Public read access" ON intelligence_feed FOR SELECT USING (true);