-- 1. PULIZIA TOTALE (Reset)
-- Cancelliamo le tabelle nell'ordine corretto per evitare conflitti di dipendenza
DROP TABLE IF EXISTS technical_signals;
DROP TABLE IF EXISTS market_insights;
DROP TABLE IF EXISTS intelligence_feed;
DROP TABLE IF EXISTS sources;
DROP TABLE IF EXISTS assets;

-- 2. RICREAZIONE TABELLE (Tutte sincronizzate su BIGINT)

-- Tabella ASSET
create table assets (
  ticker text primary key, -- Es: 'XAUUSD'
  name text,
  type text
);

-- Popoliamo dati base
insert into assets (ticker, name, type) values 
('XAUUSD', 'Gold', 'COMMODITY'),
('EURUSD', 'Euro Dollar', 'FOREX'),
('BTCUSD', 'Bitcoin', 'CRYPTO'),
('SPX500', 'S&P 500', 'INDEX'),
('NQ100', 'Nasdaq', 'INDEX'),
('DJ30', 'Dow Jones', 'INDEX')
on conflict do nothing;

-- Tabella SOURCES
create table sources (
  id bigint generated by default as identity primary key, -- TIPO BIGINT
  name text unique not null,
  base_url text
);

-- Tabella INTELLIGENCE_FEED
create table intelligence_feed (
  id bigint generated by default as identity primary key, -- TIPO BIGINT
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  source_id bigint references sources(id), -- Collegamento BIGINT -> BIGINT
  title text,
  url text unique not null,
  published_at timestamp with time zone,
  content text, 
  summary text,
  raw_metadata jsonb
);

-- Tabella MARKET_INSIGHTS
create table market_insights (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  video_id bigint references intelligence_feed(id) on delete cascade, -- Collegamento BIGINT -> BIGINT (Ora funziona)
  asset_ticker text, 
  sentiment text check (sentiment in ('BULLISH', 'BEARISH', 'NEUTRAL')),
  timeframe text, 
  key_levels text,
  ai_reasoning text
);

-- Tabella TECHNICAL_SIGNALS
create table technical_signals (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  asset_ticker text references assets(ticker),
  pattern text, 
  direction text check (direction in ('LONG', 'SHORT')),
  status text default 'PENDING', 
  notes text
);