from typing import Any

def account_info() -> Any: ...
def copy_rates_from(symbol, timeframe, date_from, count) -> Any: ...
def copy_rates_from_pos(symbol, timeframe, start_pos, count) -> Any: ...
def copy_rates_range(symbol, timeframe, date_from, date_to) -> Any: ...
def copy_ticks_from(symbol, date_from, count, flags) -> Any: ...
def copy_ticks_range(symbol, date_from, date_to, flags) -> Any: ...
def history_deals_get(*args, **kwargs): ...
def history_deals_total(date_from, date_to) -> Any: ...
def history_orders_get(*args, **kwargs): ...
def history_orders_total(date_from, date_to) -> Any: ...
def initialize(*args, **kwargs): ...
def last_error() -> Any: ...
def login(*args, **kwargs): ...
def market_book_add(symbol) -> Any: ...
def market_book_get(symbol) -> Any: ...
def market_book_release(symbol) -> Any: ...
def order_calc_margin(action, symbol, volume, price) -> Any: ...
def order_calc_profit(action, symbol, volume, price_open, price_close) -> Any: ...
def order_check(request) -> Any: ...
def order_send(request) -> Any: ...
def orders_get(*args, **kwargs): ...
def orders_total() -> Any: ...
def positions_get(*args, **kwargs): ...
def positions_total() -> Any: ...
def shutdown() -> Any: ...
def symbol_info(symbol) -> Any: ...
def symbol_info_tick(symbol) -> Any: ...
def symbol_select(*args, **kwargs): ...
def symbols_get(*args, **kwargs): ...
def symbols_total() -> Any: ...
def terminal_info() -> Any: ...
def version() -> Any: ...
